### ISSUE TITLE
Error with PHPUnit 7.x

### ISSUE THREAD

**Issue by JeroenDeDauw** [oradwell/covers-validator#21]
Even though the CI here passes with PHPUNit 7.x, in my project I get an error when I use covers-validator with 7.x instead of 6.x:

```
CoversValidator 0.7.0

Fatal error: Uncaught Error: Class 'PHPUnit\Util\Fileloader' not found in /app/vendor/ockcyp/covers-validator/src/Loader/FileLoader.php:16
Stack trace:
#0 /app/vendor/ockcyp/covers-validator/src/Handler/InputHandler.php(31): OckCyp\CoversValidator\Loader\FileLoader::loadFile('/app/tests/boot...')
#1 /app/vendor/ockcyp/covers-validator/src/Command/ValidateCommand.php(52): OckCyp\CoversValidator\Handler\InputHandler::handleInput(Object(Symfony\Component\Console\Input\ArgvInput))
#2 /app/vendor/symfony/console/Command/Command.php(252): OckCyp\CoversValidator\Command\ValidateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /app/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /app/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OckCyp\CoversVal in /app/vendor/ockcyp/covers-validator/src/Loader/FileLoader.php on line 16
```

**Comment by oradwell** [comment]
are you using the phar build?

**Comment by oradwell** [comment]
it seems the class name is wrong for PHPUnit 7.x (`PHPUnit\Util\Fileloader`: they made the L uppercase in 7.x). I think we should still be able to support both using `class_exists`. Would you be able to test and create a PR?

https://github.com/oradwell/covers-validator/blob/d3209391e25ed618d82f7f81031e1f749c83a9eb/src/Loader/FileLoader.php#L5
